apiVersion: v1
kind: Service
metadata:
  name: comingsoon-page
  namespace: comingsoon
spec:
  selector:
    app: comingsoon-page
  type: NodePort
  ports:
  - protocol: TCP
    port: 80 # listen to port 80  
    targetPort: 80 # send to which container port