pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
    stages {
        stage('Docker Login') {
            steps {
                // Add --password-stdin to run docker login command non-interactively
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
                sh """
                cd Simple-Project/
                docker build -t test .
		docker tag test ahmedmosaad112/test
  		docker push ahmedmosaad112/test
    		docker run -d --name test -p 5000:80 ahmedmosaad112/test
                """
            }
        }
    } 
}
